server:
  port: 8082
spring:
  application:
    name: job # 服务名
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: false # 不需要将自己注册到consul
  redis:
    host: 192.168.200.129
    password: chongba
    port: 6379
  output:
    ansi:
      enabled: always